# Generated by Django 3.1.2 on 2020-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(default='Author Background', max_length=300),
            preserve_default=False,
        ),
    ]
